### ISSUE TITLE
Update go-smilo with Autonity 0.4.0

### ISSUE THREAD

**Issue by thomasmodeneis** [smilofoundation/go-smilo#47]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by donmiguelenriquez** [comment]
done
